# Generated by Django 2.2.1 on 2019-05-11 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('evaluate', models.FloatField(blank=True)),
                ('station', models.CharField(blank=True, max_length=30)),
                ('genre', models.CharField(blank=True, max_length=30)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('coordinate', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
