# Generated by Django 2.2.1 on 2019-06-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190528_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='photo_binary',
            field=models.BinaryField(blank=True),
        ),
    ]
