# Generated by Django 2.2.1 on 2019-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shop_photo_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
    ]
