# Generated by Django 2.2.1 on 2019-06-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190626_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
