# Generated by Django 2.2.1 on 2019-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190626_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='photo_binary',
        ),
        migrations.AddField(
            model_name='shop',
            name='dinner_bud',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='kuchikomi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='lunch_bud',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='teikyu',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='evaluate',
            field=models.FloatField(null=True),
        ),
    ]
