# Generated by Django 2.2.1 on 2019-07-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190728_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='photo',
        ),
    ]
