# Generated by Django 2.2.1 on 2019-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190509_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='station',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
